[supervisord]
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:fastapi]
directory=/app/src/
environment=NGX_PORT="%(ENV_NGX_PORT)s"
command=python -m uvicorn main:app --host 0.0.0.0 --port %(ENV_NGX_PORT)s --workers 4
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
