import type { Column, Row } from '$lib/types/table';
import type { SvelteSet } from 'svelte/reactivity';
import type { RenderItem } from './table.utils';

export interface TableGridProps {
	sortedColumns: Column[];
	renderItems: RenderItem[];
	loading: boolean;
	tableMinWidth: number;
	addingRow: boolean;
	deletingRowId: number | null;
	rowsWithDocs: SvelteSet<string>;
	editingCell: { rowId: number; colId: string } | null;
	editValue: string;
	renamingColId: string | null;
	renameValue: string;
	colMenuId: string | null;
	tagsPopupCell: { rowId: number; colId: string } | null;
	sortConfig: { colId: string; dir: 'asc' | 'desc' } | null;
	collapsedGroups: SvelteSet<string>;
	localWidths: Record<string, number>;
	onStartEdit: (rowId: number, col: Column, currentVal: unknown) => void;
	onCommitEdit: (rowId: number, col: Column) => void;
	onEditValueChange: (val: string) => void;
	onEditingCellChange: (cell: { rowId: number; colId: string } | null) => void;
	onToggleCheckbox: (rowId: number, col: Column) => void;
	onRemoveTag: (rowId: number, col: Column, tag: string) => void;
	onAddTag: (rowId: number, col: Column, tag: string) => void;
	onTagsPopupChange: (cell: { rowId: number; colId: string } | null) => void;
	onDeleteRow: (rowId: number) => void;
	onOpenExpand: (row: Row) => void;
	onOpenContextMenu: (e: MouseEvent, type: 'row' | 'col', id: string) => void;
	onStartRename: (colId: string, name: string) => void;
	onCommitRename: (colId: string) => void;
	onRenameValueChange: (val: string) => void;
	onRenamingColIdChange: (id: string | null) => void;
	onColMenuChange: (colId: string | null) => void;
	onSortChange: (config: { colId: string; dir: 'asc' | 'desc' } | null) => void;
	onFilterAdd: (colId: string) => void;
	onShowFilterPanel: () => void;
	onHideCol: (colId: string) => void;
	onDeleteColumn: (colId: string) => void;
	onMoveColumn: (col: Column, dir: 'up' | 'down') => void;
	onResizeStart: (e: MouseEvent, col: Column) => void;
	onShowAddColumn: () => void;
	onAddRow: () => void;
	onAddRowAndEdit?: (colId: string) => void;
	onAddRowInGroup: (key: string, col: Column) => void;
	onToggleCollapseGroup: (key: string) => void;
	onManageOptions: (col: Column) => void;
	onOpenDocCell: (row: Row, col: Column) => void;
	addingColumn?: boolean;
	scrollToRowId?: number | null;
	scrollToColTrigger?: number;
}
