-- Roles (no login)
CREATE ROLE dba;
CREATE ROLE app;
CREATE ROLE login_mgr;

-- DBA: full DDL on current and future objects
GRANT ALL ON SCHEMA public TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO dba;

-- App: CRUD on future data tables, USAGE on sequences
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO app;

-- Login manager: SELECT/INSERT/UPDATE on future auth tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO login_mgr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO login_mgr;
